# Render configuration for the Universal RAG System
# Docs: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: universal-rag-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PINECONE_API_KEY
        fromService:
          name: pinecone
          type: secret
          property: apiKey
      - key: GOOGLE_API_KEY
        fromService:
          name: google-genai
          type: secret
          property: apiKey
      - key: PINECONE_INDEX_NAME
        value: hackerx

# Uncomment and configure these if you want to use Render's managed services
# databases:
#   - name: pinecone
#     databaseName: pinecone
#     user: pinecone
#     plan: free
#   - name: google-genai
#     databaseName: google-genai
#     user: google-genai
#     plan: free
