# Render configuration for the Universal RAG System
# Docs: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: universal-rag-system
    env: python
    region: oregon  # Choose a region close to your users
    plan: free  # Explicitly set to free tier
    buildCommand: |
      pip install --no-cache-dir -r requirements.txt
    startCommand: |
      # Set Python memory management variables
      export PYTHONUNBUFFERED=1
      export PYTHONDONTWRITEBYTECODE=1
      # Limit worker memory usage
      export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128
      # Start the server with a single worker to save memory
      uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1 --limit-max-requests 1000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
      - key: PINECONE_API_KEY
        fromService:
          name: pinecone
          type: secret
          property: apiKey
      - key: GOOGLE_API_KEY
        fromService:
          name: google-genai
          type: secret
          property: apiKey
      - key: PINECONE_INDEX_NAME
        value: hackerx

# Uncomment and configure these if you want to use Render's managed services
# databases:
#   - name: pinecone
#     databaseName: pinecone
#     user: pinecone
#     plan: free
#   - name: google-genai
#     databaseName: google-genai
#     user: google-genai
#     plan: free
